spring.application.name=ecober
# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/ecober?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=A!7904039823a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gmap.api.key=${GMAP_API_KEY}
openrouter.api.key=${OPENROUTER_API_KEY}
